#!/bin/bash

# Pfad zur bg-saved.cfg von nitrogen
config_file="$HOME/.config/nitrogen/bg-saved.cfg"

# Letztes bekanntes Wallpaper speichern
last_wallpaper_file="$HOME/.cache/last_wallpaper"

update_pywal() {
    current_wallpaper=$(grep "file=" "$config_file" | cut -d '=' -f2)

    # Prüfen, ob das Wallpaper sich geändert hat
    if [ ! -f "$last_wallpaper_file" ] || [ "$current_wallpaper" != "$(cat $last_wallpaper_file)" ]; then
        
        wal -qi "$current_wallpaper" && wait && pywalfox update && wait && ./polybarstartscript 
	sleep 3 
        echo "$current_wallpaper" > "$last_wallpaper_file"
    fi
}

while inotifywait -e close_write "$config_file"; do
    update_pywal
done

